### ISSUE TITLE
Fix behat config for Chrome 95

### ISSUE THREAD

**Issue by derschatta** [totara/totara-docker-dev#187]
Currently the configuration for behat in the config.php is not 100% compatible with Chrome 95. 

We need to make sure it includes the following:

```
            "goog:chromeOptions":
              args:
                - '--disable-infobars'
                - '--disable-background-timer-throttling'
                - '--disable-backgrounding-occluded-windows'
              prefs:
                credentials_enable_service: false
              w3c: false
              excludeSwitches:
                - enable-automation
```
