### ISSUE TITLE
Mysql 5.7 on M1

### ISSUE THREAD

**Issue by benfes** [totara/totara-docker-dev#230]
The mysql 5.7 image does not work on m1 macs. (mysql 8.0 works fine)

To get around this you can force the platform on the container definition in `mysql.yml` to be amd64 running on linux (`platform: linux/x86_64`). Bit of a hack but it works:

```yml
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: totara_mysql57
    ports:
```
