### ISSUE TITLE
Missing Alias Entries

### ISSUE THREAD

**Issue by codyfinegan** [totara/totara-docker-dev#280]
Both the nginx.yml and apache.yml files have not got the newer 8.2 & 8.3 images listed as aliases.

**To Reproduce**
View https://github.com/totara/totara-docker-dev/blob/master/compose/nginx.yml or https://github.com/totara/totara-docker-dev/blob/master/compose/apache.yml

```
networks:
      totara:
        aliases:
          ...
          - totara80
          - totara80.behat
          - totara80.behat.totaralms.com
          - totara81
          - totara81.behat
          - totara81.behat.totaralms.com
```

Add in the instances for totara82 & 83
